<a href="https://colab.research.google.com/github/boscoybarra/algebra-basics-with-numpy-cheat-sheet/blob/master/Numpy_Arrays_Cheat_Sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from numpy import array


In [0]:
# create array
l = [1.0, 2.0, 3.0]
a = array(l)

In [0]:
# display array
print(a)

[1. 2. 3.]


In [0]:
# display array shape
print(a.shape)

(3,)


In [0]:
# display array data type
print(a.dtype)

float64


In [0]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[3.60814402e-316 1.09802054e-311 7.51470620e+199]
 [6.67771196e+151 6.01737305e+175 7.28577035e+199]
 [3.42134197e+180 3.38461351e+125 4.99809053e+228]]


In [0]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


##Combining Arrays

In [0]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [0]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


In [0]:
b1 = array([7,8,9])
b2 = array([10,11,12])

In [0]:
b3 = vstack((b1, b2))
print(b3)

[[ 7  8  9]
 [10 11 12]]


In [0]:
print(a2.shape)
print(b3.shape)

(3,)
(2, 3)


In [0]:

from numpy import transpose
transpose(a2)
print(b3)
print(a2)

[[ 7  8  9]
 [10 11 12]]
[4 5 6]


## Array Indexing

In [0]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


In [0]:
# index two-dimensional array
from numpy import array
# define array
data = array([
  [11, 22],
  [33, 44],
  [55, 66]])
# index data
print(data[0,0])

11


In [0]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
  [11, 22],
  [33, 44],
  [55, 66]])
# index data
print(data[0,])

[11 22]


## Array Slicing

data[from:to]

In [0]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[1:])

[22 33 44 55]


In [0]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [0]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


## Two-Dimensional Slicing

SyntaxError: ignored

X = [:, :-1]
    [#row , #column]

In [0]:
# split input and output data
from numpy import array
# define array
data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])
# separate data
#For the input "X" features, we can select all rows and all columns except the last one by specifying : for in the rows index, and :-1 in the columns index.
X, y = data[:, :-2], data[:, -1] #For the output "y" column, we can select all rows again using : and index just the last column by specifying the -1 index.
print(data.shape)
print(X)
print(y)

(3, 3)
[[11]
 [44]
 [77]]
[33 66 99]


Split Train and Test Rows
It is common to split a loaded dataset into separate train and test sets. This is a splitting of rows where some portion will be used to train the model and the remaining portion will be used to estimate the skill of the trained model. This would involve slicing all columns by specifying : in the second dimension index. The training dataset would be all rows from the beginning to the split point.

In [0]:
# split train and test data
from numpy import array
# define array
data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)  

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


##  Array Reshaping

In [0]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [0]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [0]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
 [33, 44],
 [55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0]) 
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


## Reshape 1D to 2D Array


In [0]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


In [0]:
print(data)

[[11]
 [22]
 [33]
 [44]
 [55]]


## Reshape 2D to 3D Array

In [0]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


In [0]:
print(data)

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


## Array Broadcasting


In [0]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
print(a.shape)
# define scalar
b=2 
print(b)
# print(b.shape)
# broadcast 
c=a+b
print(c)

[1 2 3]
(3,)
2
[3 4 5]


In [0]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
print(A.shape)
# define one-dimensional array 
b = array([1, 2, 3])
print(b)
print(b.shape)
# broadcast
C=A+b
print(C)

[[1 2 3]
 [1 2 3]]
(2, 3)
[1 2 3]
(3,)
[[2 4 6]
 [2 4 6]]


In [0]:
import numpy as np

x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))

z = np.maximum(x, y)
print(z)


[[[[0.9483574  0.63370856 0.60249399 ... 0.45271774 0.93409257
    0.49993419]
   [0.50070777 0.88226051 0.8822172  ... 0.15039384 0.82277674
    0.15272299]
   [0.75639787 0.23860389 0.8373985  ... 0.47458561 0.8027014
    0.75808878]
   ...
   [0.99742034 0.84766191 0.35453016 ... 0.20157935 0.14594041
    0.93555595]
   [0.98003621 0.5829339  0.98127838 ... 0.84821052 0.72099762
    0.60982079]
   [0.30675659 0.91932964 0.94678142 ... 0.73863481 0.94496858
    0.12233423]]

  [[0.9483574  0.45186088 0.84590154 ... 0.39628905 0.54118514
    0.32041433]
   [0.50070777 0.88226051 0.88949399 ... 0.60158675 0.63819602
    0.85749394]
   [0.75639787 0.60075607 0.8373985  ... 0.7776064  0.8027014
    0.73372846]
   ...
   [0.86975094 0.84766191 0.58152097 ... 0.20157935 0.97919704
    0.93555595]
   [0.89311911 0.5829339  0.98127838 ... 0.84821052 0.63291245
    0.48057277]
   [0.34944279 0.91932964 0.88543806 ... 0.79868528 0.44691742
    0.31301432]]

  [[0.9483574  0.45186088 0.65463854

## Vector

In [0]:
# create a vector
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


In [0]:
# vector division
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3]) 
print(b)
# divide vectors 
c=a/b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


## Vector Dot Product

In [0]:
# vector dot product
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [0]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

In [0]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [0]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [0]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [0]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
  [0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
# rank 1
M1 = array([
[1,2],
  [1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
# rank 2
M2 = array([
[1,2],
  [3,14]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[ 1  2]
 [ 3 14]]
2


## Sparse Matrices

In [0]:
# sparse matrix
from numpy import array
from scipy.sparse import csr_matrix
# create dense matrix
A = array([
  [1, 0, 0, 1, 0, 0],
  [0, 0, 2, 0, 0, 1],
  [0, 0, 0, 2, 0, 0]])
print(A)
# convert to sparse matrix (CSR method)
S = csr_matrix(A)
# S tells us where the non-zero value is located
print(S)
# reconstruct dense matrix
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


We can also calculate sparsity like such

In [0]:
# sparsity calculation
from numpy import array
from numpy import count_nonzero
# create dense matrix
A = array([
  [1, 0, 0, 1, 0, 0],
  [0, 0, 2, 0, 0, 1],
  [0, 0, 0, 2, 0, 0]])
print(A)
# calculate sparsity
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222


Other example

In [0]:
# sparsity calculation
from numpy import array
from numpy import count_nonzero
# create dense matrix
A = array([
  [1, 2, 3, 2, 0, 0],
  [0, 0, 4, 0, 1, 2],
  [0, 0, 0, 4, 0, 0]])
print(A)
# calculate sparsity
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

[[1 2 3 2 0 0]
 [0 0 4 0 1 2]
 [0 0 0 4 0 0]]
0.5555555555555556


## Tensors

In [0]:
# tensor addition
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# add tensors
C=A+B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [0]:
# tensor subtraction
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# subtract tensors
C=A-B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


Here, we will use the ◦ operator to indicate the Hadamard product operation between tensors.

In [0]:
# tensor Hadamard product
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# multiply tensors
C=A*B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [0]:
# tensor division
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]])
# divide tensors
C=A/B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [0]:
# tensor product
from numpy import array
from numpy import tensordot
# define first vector
A = array([1,2])
# define second vector
B = array([3,4])
# calculate tensor product
C = tensordot(A, B, axes=0)
print(C)

# It is different multiplying, it does not respect the number of dimensions.
D = A * B
print(D)

#Notice that depending on how we make the product of one or the other the position chagnes

F = tensordot(B, A, axes=0)
print(F)

[[3 4]
 [6 8]]
[3 8]
[[3 6]
 [4 8]]


In [0]:
A.shape

(2,)

In [0]:
D.shape

(2,)

## LU Decomposition

In [0]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)

# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)

# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## QR Decomposition


In [0]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
  [1, 2],
  [3, 4],
  [5, 6]])
print(A)
# factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


## Cholesky decomposition

In [0]:
# Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define symmetrical matrix
A = array([
  [2, 1, 1],
  [1, 2, 1],
  [1, 1, 2]])
print(A)
# factorize
L = cholesky(A)
print(L)
# reconstruct
B = L.dot

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


## Eigendecomposition

In [0]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
   [7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [0]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
# factorize
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [0]:
# reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## SDV

In [0]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
  [1, 2],
  [3, 4],
  [5, 6]])
print(A)
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [0]:
# reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
  [1, 2],
  [3, 4],
  [5, 6]])
print(A)
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [0]:
# reconstruct square matrix from svd
from numpy import array
from numpy import diag
from scipy.linalg import svd
# define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)
# factorize
U, s, V = svd(A)

# create n x n Sigma matrix
Sigma = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## pseudoinverse

In [1]:
# pseudoinverse
from numpy import array
from numpy.linalg import pinv
# define matrix
A = array([
  [0.1, 0.2],
  [0.3, 0.4],
  [0.5, 0.6],
  [0.7, 0.8]])
print(A)
# calculate pseudoinverse
B = pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.42385628e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


## Dimensionality Reduction

In [2]:
# data reduction with svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
  [1,2,3,4,5,6,7,8,9,10],
  [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])
print(A)
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(V))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(V.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [3]:
# svd data reduction in scikit-learn
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define matrix
A = array([
  [1,2,3,4,5,6,7,8,9,10],
  [11,12,13,14,15,16,17,18,19,20],
  [21,22,23,24,25,26,27,28,29,30]])
print(A)
# create transform
svd = TruncatedSVD(n_components=2)
# fit transform
svd.fit(A)
# apply transform
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


# Multivariate Statistics


## Expected Value and Mean

In [4]:
# vector mean
from numpy import array
from numpy import mean
# define vector
v = array([1,2,3,4,5,6])
print(v)
# calculate mean
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [5]:
# matrix means
from numpy import array
from numpy import mean
# define matrix
M = array([
  [1,2,3,4,5,6],
  [1,2,3,4,5,6]])
print(M)
# column means
col_mean = mean(M, axis=0)
print(col_mean)
# row means
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


## Variance and Standard Deviation