<a href="https://colab.research.google.com/github/boscoybarra/algebra-basics-with-numpy-cheat-sheet/blob/master/Numpy_Arrays_Cheat_Sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from numpy import array


In [0]:
# create array
l = [1.0, 2.0, 3.0]
a = array(l)

In [0]:
# display array
print(a)

[1. 2. 3.]


In [0]:
# display array shape
print(a.shape)

(3,)


In [0]:
# display array data type
print(a.dtype)

float64


In [0]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[3.60814402e-316 1.09802054e-311 7.51470620e+199]
 [6.67771196e+151 6.01737305e+175 7.28577035e+199]
 [3.42134197e+180 3.38461351e+125 4.99809053e+228]]


In [0]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


##Combining Arrays

In [0]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [0]:
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


In [0]:
b1 = array([7,8,9])
b2 = array([10,11,12])

In [0]:
b3 = vstack((b1, b2))
print(b3)

[[ 7  8  9]
 [10 11 12]]


In [0]:
print(a2.shape)
print(b3.shape)

(3,)
(2, 3)


In [0]:

from numpy import transpose
transpose(a2)
print(b3)
print(a2)

[[ 7  8  9]
 [10 11 12]]
[4 5 6]


## Array Indexing

In [0]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


In [0]:
# index two-dimensional array
from numpy import array
# define array
data = array([
  [11, 22],
  [33, 44],
  [55, 66]])
# index data
print(data[0,0])

11


In [0]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([
  [11, 22],
  [33, 44],
  [55, 66]])
# index data
print(data[0,])

[11 22]


## Array Slicing

data[from:to]

In [0]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[1:])

[22 33 44 55]


In [0]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [0]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


## Two-Dimensional Slicing

SyntaxError: ignored

X = [:, :-1]
    [#row , #column]

In [0]:
# split input and output data
from numpy import array
# define array
data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])
# separate data
#For the input "X" features, we can select all rows and all columns except the last one by specifying : for in the rows index, and :-1 in the columns index.
X, y = data[:, :-2], data[:, -1] #For the output "y" column, we can select all rows again using : and index just the last column by specifying the -1 index.
print(data.shape)
print(X)
print(y)

(3, 3)
[[11]
 [44]
 [77]]
[33 66 99]


Split Train and Test Rows
It is common to split a loaded dataset into separate train and test sets. This is a splitting of rows where some portion will be used to train the model and the remaining portion will be used to estimate the skill of the trained model. This would involve slicing all columns by specifying : in the second dimension index. The training dataset would be all rows from the beginning to the split point.

In [0]:
# split train and test data
from numpy import array
# define array
data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)  

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


##  Array Reshaping

In [0]:
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [0]:
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)

(3, 2)


In [0]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
 [33, 44],
 [55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0]) 
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


## Reshape 1D to 2D Array


In [0]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

(5,)
(5, 1)


In [0]:
print(data)

[[11]
 [22]
 [33]
 [44]
 [55]]


## Reshape 2D to 3D Array

In [0]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


In [0]:
print(data)

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


## Array Broadcasting


In [0]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
print(a.shape)
# define scalar
b=2 
print(b)
# print(b.shape)
# broadcast 
c=a+b
print(c)

[1 2 3]
(3,)
2
[3 4 5]


In [0]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
print(A.shape)
# define one-dimensional array 
b = array([1, 2, 3])
print(b)
print(b.shape)
# broadcast
C=A+b
print(C)

[[1 2 3]
 [1 2 3]]
(2, 3)
[1 2 3]
(3,)
[[2 4 6]
 [2 4 6]]


In [0]:
import numpy as np

x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))

z = np.maximum(x, y)
print(z)


[[[[0.9483574  0.63370856 0.60249399 ... 0.45271774 0.93409257
    0.49993419]
   [0.50070777 0.88226051 0.8822172  ... 0.15039384 0.82277674
    0.15272299]
   [0.75639787 0.23860389 0.8373985  ... 0.47458561 0.8027014
    0.75808878]
   ...
   [0.99742034 0.84766191 0.35453016 ... 0.20157935 0.14594041
    0.93555595]
   [0.98003621 0.5829339  0.98127838 ... 0.84821052 0.72099762
    0.60982079]
   [0.30675659 0.91932964 0.94678142 ... 0.73863481 0.94496858
    0.12233423]]

  [[0.9483574  0.45186088 0.84590154 ... 0.39628905 0.54118514
    0.32041433]
   [0.50070777 0.88226051 0.88949399 ... 0.60158675 0.63819602
    0.85749394]
   [0.75639787 0.60075607 0.8373985  ... 0.7776064  0.8027014
    0.73372846]
   ...
   [0.86975094 0.84766191 0.58152097 ... 0.20157935 0.97919704
    0.93555595]
   [0.89311911 0.5829339  0.98127838 ... 0.84821052 0.63291245
    0.48057277]
   [0.34944279 0.91932964 0.88543806 ... 0.79868528 0.44691742
    0.31301432]]

  [[0.9483574  0.45186088 0.65463854

## Vector

In [0]:
# create a vector
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


In [0]:
# vector division
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3]) 
print(b)
# divide vectors 
c=a/b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


## Vector Dot Product

In [0]:
# vector dot product
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


## Matrix

In [1]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [2]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [3]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
  [0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


## Matrix Operations

In [4]:
# transpose matrix
from numpy import array
# define matrix
A = array([
  [1, 2],
  [3, 4],
  [5, 6]])
print(A)
# calculate transpose
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [12]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
  [3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

# First, we define a small 2 × 2 matrix, then calculate the inverse of the matrix, and then confirm the inverse by multiplying it with the original matrix to give the identity matrix. Running the example prints the original, inverse, and identity matrices.

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [13]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15
